version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: meals
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: meals
      JWTSECRET: jwtsecret
      CLIENT_URL: http://localhost:3000
      PORT: 8080
    command: bash -c "./wait-for-it.sh db:5432 -- go run db/migrate.go && go run main.go"
    volumes:
      - .:/go/src/meals-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
