on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: meals
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
#      - name: Make envfile
#        uses: SpicyPizza/create-envfile@v1
#        with:
#          PORT: 8080
#          HOST: 0.0.0.0
#          DB_HOST: localhost
#          DB_PORT: 5432
#          DB_USER: postgres
#          DB_PASSWORD: postgres
#          DB_NAME: meals
#          file_name: .env
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
        env:
          PORT: 8080
          HOST: 0.0.0.0
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: meals
